export async function seed(knex) {
  await knex("shops").del();
  await knex("shops").insert([
    {
      id: 1,
      name: "Kindly",
      street_number: "110",
      street_name: "Dyke Road",
      city: "Brighton",
      postcode: "BN1 3TE",
      coordinates: "[-0.147544, 50.831252]",
      is_active: "1",
    },
    {
      id: 2,
      name: "Seed N Sprout",
      street_number: "82",
      street_name: "St George's Road",
      city: "Brighton",
      postcode: "BN2 1EF",
      coordinates: "[-0.118654603294007, 50.817787829680455]",
      is_active: "1",
    },
    {
      id: 3,
      name: "Rice & Beans",
      street_number: "3",
      street_name: "College Place",
      city: "Brighton",
      postcode: "BN1 1AE",
      coordinates: "[-0.115808, 50.817313]",
      is_active: "0",
    },
    {
      id: 4,
      name: "Twenty Six Foods",
      street_number: "26",
      street_name: "Oxford Street",
      city: "Brighton",
      postcode: "BN1 1AE",
      coordinates: "[-0.119869, 50.843273]",
      is_active: "0",
    },
    {
      id: 5,
      name: "Cabbage",
      street_number: "67",
      street_name: "Lamond Street",
      city: "London",
      postcode: "NW1 1AE",
      coordinates: "[-0.097729, 51.518096]",
      is_active: "1",
    },
    {
      id: 6,
      name: "One Away",
      street_number: "6",
      street_name: "Lamond Burn",
      city: "London",
      postcode: "NW1 1AE",
      coordinates: "[-0.095729, 51.518096]",
      is_active: "0",
    },
    {
      id: 7,
      name: "Also One Away",
      street_number: "7",
      street_name: "Lamond Drive",
      city: "London",
      postcode: "NW1 1AE",
      coordinates: "[-0.097729, 51.718096]",
      is_active: "0",
    },
    {
      id: 8,
      name: "Green Grove",
      street_number: "51",
      street_name: "Kingsland High Street",
      city: "London",
      postcode: "E8 2JS",
      coordinates: "[-0.075221, 51.546794]",
      is_active: "1",
    },
    {
      id: 9,
      name: "Nourish & Nurture",
      street_number: "87",
      street_name: "Ridley Road",
      city: "London",
      postcode: "E8 2NP",
      coordinates: "[-0.071129, 51.548605]",
      is_active: "1",
    },
    {
      id: 10,
      name: "The Organic Basket",
      street_number: "24",
      street_name: "Shacklewell Lane",
      city: "London",
      postcode: "E8 2DE",
      coordinates: "[-0.071611, 51.551834]",
      is_active: "1",
    },
    {
      id: 11,
      name: "Pure Harvest",
      street_number: "17",
      street_name: "Dalston Lane",
      city: "London",
      postcode: "E8 3DF",
      coordinates: "[-0.073345, 51.547263]",
      is_active: "1",
    },
    {
      id: 12,
      name: "Wholesome Wonders",
      street_number: "19",
      street_name: "Stoke Newington Road",
      city: "London",
      postcode: "N16 8BH",
      coordinates: "[-0.075993, 51.552117]",
      is_active: "1",
    },
    {
      id: 13,
      name: "Healthy Haven",
      street_number: "103",
      street_name: "Balls Pond Road",
      city: "London",
      postcode: "N1 4BW",
      coordinates: "[-0.085932, 51.545758]",
      is_active: "1",
    },
    {
      id: 14,
      name: "The Green Pantry",
      street_number: "27",
      street_name: "Mildmay Park",
      city: "London",
      postcode: "N1 4NA",
      coordinates: "[-0.085315, 51.548263]",
      is_active: "1",
    },
    {
      id: 15,
      name: "Natural Nourishment",
      street_number: "56",
      street_name: "Southgate Road",
      city: "London",
      postcode: "N1 3JF",
      coordinates: "[-0.089721, 51.539627]",
      is_active: "1",
    },
    {
      id: 16,
      name: "Organic Origins",
      street_number: "33",
      street_name: "Highbury New Park",
      city: "London",
      postcode: "N5 2EU",
      coordinates: "[-0.094384, 51.554922]",
      is_active: "1",
    },
    {
      id: 17,
      name: "Pure & Simple",
      street_number: "12",
      street_name: "Queensbridge Road",
      city: "London",
      postcode: "E2 8NP",
      coordinates: "[-0.073481, 51.535291]",
      is_active: "1",
    },
  ]);
}
